dist: bionic

language: go
sudo: false

matrix:
  include:
    - go: 1.13.x
      env:
        - ARTIFACT=true
    # - go: 1.12.x
  allow_failures:
    # - go: 1.14.x

env:
  global:
    # Enable Go Module Support
    - GO111MODULE=on

before_install:
  - go get github.com/mitchellh/gox

install:
  - # skip

script:
  - set -e
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d .)
  - go vet $(go list ./... | grep -v /vendor/)
  - go test -v -race ./...
  - | # Only build binaries from the supported Go version
      if [ "${ARTIFACT}" = "true" ]; then
        gox -os="windows" \
            -arch="amd64" \
            -output="release/gontlm-proxy_{{.OS}}_{{.Arch}}" \
            -ldflags "-X main.Rev=`git rev-parse --short HEAD`" \
            -verbose ./...;
        find release/* -type f -exec sh -c 'sha256sum {} | cut -f1 -d" " > {}.SHA256SUM' \;
      fi
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "UL5PzHI4OlnyobtTBj0TJYkYFseutN4mauCvhLbGpIBrH6qXa0ZPDOW2uunR4+WeSOqdkqN97vjXIIVkBlMz2JBC9gRlNlWkRjiMIFX3Mo6I2BmcbnnDtfDDOjQ8FxnBzb6Dm7k9jRj7xn3S6GmyHpe3a6ysNfnM9UKjzkX7MUUnCOWWeKxiMi5/sgjvEtTBEEA8CH2LjLgU96DL8T2h80MOAhYHdKfPw2WNFadBYaVTvmZYxYaYg1xiwBC0PhNn4hikRMYd/RO8rdJzLgWVX395/SYuoX9Ju4HUv+ij4t2aYZknpa05c/tlN1lCdHEAgKWxB1We2hZdWNDyVWlatpRd8k+bw8iQnX6W7SuksV/2frfmxoNbVD9pCfdQaGT2fiy5nzX5nlRcpyX3SElKKMZRdIs3DtEmzKsDK1G/HmUUcMGk9epGThapgtpHq6qUzy5Ayfcd+uDrisw1QTkaCGV/jfzaA2r0Tn9FDL9jogFeHthglweu2mafxHHzdgifTiOS83en+3jyaKAVQCYZqskjLWhHw2KtSjDNVsUYxtQaodHZlQLs1kT42tRx1LFkq5ksHU3weAA3n3zFddeOrZOYx605Bkl4dEaE3Z3Hn+gL5lyPYdawKg7m0rLhuSA7I0N74zbFLuWdSwjY2Q3wCgPWTU+tS9Am9zYS37Obdyw="
  file:
    - release/gontlm-proxy_windows_amd64.exe
    - release/gontlm-proxy_windows_amd64.exe.SHA256SUM
    # - release/gontlm-proxy_darwin_amd64
    # - release/gontlm-proxy_darwin_amd64.SHA256SUM
    # - release/gontlm-proxy_linux_amd64
    # - release/gontlm-proxy_linux_amd64.SHA256SUM
  on:
    repo: bdwyertech/inspec-ssm-reporter
    tags: true
    condition: $ARTIFACT = true
